// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqziwvgoxopxsjmjlhyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxeml3dmdveG9weHNqbWpsaHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTU4OTEsImV4cCI6MjA3MzY5MTg5MX0.IS97Q5PqJgYCW1PO6vjwPYAO0LjFf6a8Xivjn0A9VJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});